apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
        - name: nginx-controller
          image: nginx
  replicas: 2
